import type { DrillDefinition, TrialSpec, ProgressionLevel, TargetZone } from "@/ares/drillTypes";
import { strikePosition, PERIPHERAL_ZONES } from "../shared/zones";

/**
 * COGNITIVE CROSSFIRE — a true dual-task drill, ported whole.
 *
 * Two tasks, at the same time, competing for the same brain:
 *
 *   CENTRALLY   a cognitive problem — Go/No-Go, mental arithmetic, or a memory probe —
 *               that demands you look at it and think.
 *   PERIPHERALLY  orbs that appear out in the field and must be struck.
 *
 * The point is the INTERFERENCE. Reaching for an orb costs you the arithmetic; holding the
 * sequence in mind costs you the orb. An athlete who scores well on either task alone and
 * collapses when they run together has a divided-attention ceiling, and that ceiling is
 * exactly what a crowded field punishes. A single-task drill cannot see it.
 *
 * 315 levels, generated by the same block lattice as the original:
 *
 *   BLOCK (63 levels)   drives stimulus size (xl -> xs) and the central task
 *                       (goNoGo, math, memory, goNoGo, math)
 *   SUB-BLOCK (21)      drives the peripheral colour set (purple -> +teal -> +blue)
 *   cpIndex (7)         drives central-vs-peripheral spatial BIAS: at cpIndex 1 the orbs
 *                       cluster near the middle where you are already looking; by cpIndex 7
 *                       they are all out in the periphery and every one costs you a saccade
 *   RAMP (14)           drives the response window and the Go probability
 *
 * VR MAPPING. This is the first drill in the suite that needs BOTH input channels live at
 * once: hands STRIKE the peripheral orbs, triggers answer the centre. That is not a
 * convenience — routing both tasks through one channel would let the athlete serialise them,
 * and serialising is precisely the strategy the drill exists to prevent.
 *
 *   GO / NO-GO   green = pull the RIGHT trigger. Red = pull NOTHING. Withhold.
 *   MATH         two answers appear. LEFT trigger takes the left one, RIGHT the right one.
 *   MEMORY       a sequence flashes, then two candidates. Same left/right choice.
 */

const SESSION_MS = 60_000;
const CONCURRENT = 3;
const PX = 0.0011;                 // metres per reference pixel
const CENTRAL_Z = -1.35;           // the cognitive task sits at the fixation plane

const PURPLE = "#8B5CF6";
const TEAL = "#2998AA";
const BLUE = "#3B82F6";
const GO_GREEN = "#10B981";
const NOGO_RED = "#EF4444";
const WHITE = "#EAF0FF";
const GRAY = "#6A7086";

type PColor = "purple" | "teal" | "blue";
type CMode = "goNoGo" | "math" | "memory";

const P_HEX: Record<PColor, string> = { purple: PURPLE, teal: TEAL, blue: BLUE };
const SIZES = { xs: 30, s: 45, m: 60, l: 80, xl: 100 } as const;

/** Confusable characters — the memory foil is deliberately hard to tell from the target. */
const CONFUSABLES: Record<string, string[]> = {
  "0": ["O", "Q"], "1": ["I", "L", "7"], "2": ["Z"], "5": ["S"], "6": ["G"], "8": ["B"],
  "9": ["G", "Q"], S: ["5"], O: ["0"], Z: ["2"], G: ["6", "B"], B: ["8"], I: ["1", "L"],
};

const lerp = (a: number, b: number, t: number) => a + (b - a) * t;

/** The exact 315-level lattice. */
export function ccLevel(levelRaw: number) {
  const level = Math.min(Math.max(levelRaw || 1, 1), 315);
  const tG = (level - 1) / 314;

  const blockIdx = Math.floor((level - 1) / 63);
  const stimSize = (["xl", "l", "m", "s", "xs"] as const)[blockIdx];
  const centralMode = (["goNoGo", "math", "memory", "goNoGo", "math"] as CMode[])[blockIdx];

  const subBlockIdx = Math.floor(((level - 1) % 63) / 21);
  const peripheralMode = (["purple", "pt", "ptb"] as const)[subBlockIdx];

  const cpIndex = ((level - 1) % 7) + 1;
  const rampIdx = Math.floor(((level - 1) % 63) / 14);
  const posInRamp = ((level - 1) % 14) / 13;

  const winBase = [1500, 1700, 1600, 1500, 1400][rampIdx % 5];
  const goWindow = Math.round(winBase - (winBase - 700) * tG);

  return {
    level, tG, blockIdx, stimSize, peripheralMode, cpIndex, centralMode,
    goWindow,
    goGreenProb: Number((0.95 - 0.25 * posInRamp).toFixed(2)),
    mathProblemMs: Math.round(goWindow * (0.85 - 0.25 * tG)),
    mathAnswerMs: Math.round(goWindow * (1.0 - 0.2 * tG)),
    mathMaxOperand: 5 + blockIdx * 6,
    memoryLength: 3 + Math.floor(tG * 6),
    memoryDisplayMs: Math.round(goWindow * (0.75 - 0.2 * tG)),
    minInt: Math.round(lerp(4500, 600, tG)),
    maxInt: Math.round(lerp(7500, 1500, tG)),
  };
}

type CC = ReturnType<typeof ccLevel>;

/**
 * The central-bias map. At cpIndex 1, 60% of orbs land in the middle third — near where the
 * athlete is already looking, so the dual-task cost is small. By cpIndex 7 the bias is ZERO
 * and every orb is out in the periphery: each one now costs a saccade away from the problem,
 * and the interference is maximal. This is the drill's real difficulty axis, and it is
 * completely independent of speed.
 */
const BIAS: Record<number, number> = { 1: 0.6, 2: 0.5, 3: 0.4, 4: 0.3, 5: 0.2, 6: 0.1, 7: 0 };

function buildCCTrials(L: CC, rng: () => number): TrialSpec[] {
  const out: TrialSpec[] = [];
  const orbScale = SIZES[L.stimSize] * PX;
  const pC = BIAS[L.cpIndex] ?? 0;

  const pickColor = (): PColor => {
    if (L.peripheralMode === "purple") return "purple";
    if (L.peripheralMode === "pt") return rng() < 0.5 ? "purple" : "teal";
    const r = rng();
    return r < 0.33 ? "purple" : r < 0.66 ? "teal" : "blue";
  };

  /**
   * PERIPHERAL — three chains, so exactly three orbs are alive at all times, and the next
   * one appears the instant you clear one. The orbs do NOT expire: an ignored orb sits there
   * accruing reaction time, exactly as in the original. That is the honest cost model — the
   * penalty for abandoning the periphery is not a miss, it is a slower and slower response.
   */
  const perChain = 90; // 60s cannot drain this even at elite pace
  for (let c = 0; c < CONCURRENT; c++) {
    for (let i = 0; i < perChain; i++) {
      const color = pickColor();
      // central-bias draw: near the middle, or out in the field
      const central = rng() < pC;
      const zone: TargetZone = central
        ? (["center", "left", "right"] as TargetZone[])[Math.floor(rng() * 3)]
        : (PERIPHERAL_ZONES[Math.floor(rng() * PERIPHERAL_ZONES.length)] as TargetZone);
      const ecc = central ? 4 + rng() * 8 : 16 + rng() * 22;

      out.push({
        id: `cc-p${c}-${i}`,
        spawnAt: i === 0 ? 700 + c * 260 : -1,
        chainId: `cc-p${c}`,
        chainGapMs: 120,
        seq: i,
        duration: SESSION_MS + 5000,   // an orb never expires — it just costs you time
        kind: "go",
        zone,
        position: strikePosition(zone, ecc, 0.12, rng),
        color: P_HEX[color], emissive: P_HEX[color],
        shape: "sphere", scale: orbScale,
        meta: { pColor: color, peripheral: true },
      });
    }
  }

  /**
   * CENTRAL — a cognitive problem, every minInt..maxInt milliseconds. Answered with the
   * TRIGGERS so it cannot be serialised behind the reaching hand.
   */
  let t = 1500;
  let n = 0;
  while (t < SESSION_MS - 1200) {
    const gid = `cc-c${n}`;
    const mode = L.centralMode;

    if (mode === "goNoGo") {
      const isGo = rng() < L.goGreenProb;
      out.push({
        id: `${gid}-go`, spawnAt: t, duration: L.goWindow,
        kind: isGo ? "go" : "noGo",
        zone: "center",
        position: [0, 1.5, CENTRAL_Z],
        requiredHand: isGo ? "right" : undefined,
        color: isGo ? GO_GREEN : NOGO_RED,
        emissive: isGo ? GO_GREEN : NOGO_RED,
        shape: "sphere", scale: 0.10,
        // GREEN: pull the RIGHT trigger. RED: pull NOTHING. Withholding is the answer.
        meta: { triggerTarget: true, central: true, ctask: "goNoGo", isGo },
      });
      t += L.goWindow + L.minInt + rng() * (L.maxInt - L.minInt);
      n++;
      continue;
    }

    if (mode === "math") {
      const ops = L.level > 100 ? ["+", "-", "*"] : ["+", "-"];
      const op = ops[Math.floor(rng() * ops.length)];
      const a = 1 + Math.floor(rng() * L.mathMaxOperand);
      const b = 1 + Math.floor(rng() * a);
      const answer = op === "+" ? a + b : op === "-" ? a - b : a * b;
      const foil = answer + (rng() < 0.5 ? 1 : -1) * (1 + Math.floor(rng() * 3));
      const leftIsAnswer = rng() < 0.5;
      const optL = leftIsAnswer ? answer : foil;
      const optR = leftIsAnswer ? foil : answer;

      // 1. the problem
      out.push({
        id: `${gid}-q`, spawnAt: t, duration: L.mathProblemMs,
        kind: "distractor", decor: true, zone: "center",
        position: [0, 1.5, CENTRAL_Z],
        color: WHITE, emissive: WHITE, shape: "diamond", scale: 0.001,
        label: `${a} ${op === "*" ? "x" : op} ${b}`,
        meta: { labelInside: true, labelSize: 0.075, labelColor: WHITE },
      });
      // 2. a delay — the problem is GONE. It has to be held.
      out.push({
        id: `${gid}-d`, spawnAt: t + L.mathProblemMs, duration: 250,
        kind: "distractor", decor: true, zone: "center",
        position: [0, 1.5, CENTRAL_Z],
        color: GRAY, emissive: GRAY, shape: "diamond", scale: 0.001,
        label: "...", meta: { labelInside: true, labelSize: 0.06, labelColor: GRAY },
      });
      // 3. the two candidates
      const probeAt = t + L.mathProblemMs + 250;
      for (const [side, val] of [[-1, optL], [1, optR]] as [number, number][]) {
        out.push({
          id: `${gid}-o${side < 0 ? "L" : "R"}`, spawnAt: probeAt, duration: L.mathAnswerMs,
          kind: "distractor", decor: true, zone: "center",
          position: [side * 0.20, 1.5, CENTRAL_Z],
          color: WHITE, emissive: WHITE, shape: "diamond", scale: 0.001,
          label: String(val),
          meta: { labelInside: true, labelSize: 0.07, labelColor: WHITE },
        });
      }
      out.push({
        id: `${gid}-a`, spawnAt: probeAt, duration: L.mathAnswerMs,
        kind: "go", zone: "center",
        position: [0, 1.5, CENTRAL_Z],
        requiredHand: leftIsAnswer ? "left" : "right",
        color: WHITE, shape: "diamond", scale: 0.001,
        meta: { triggerTarget: true, central: true, ctask: "math" },
      });
      t = probeAt + L.mathAnswerMs + L.minInt + rng() * (L.maxInt - L.minInt);
      n++;
      continue;
    }

    // ---- MEMORY
    const pool = (L.level > 120 ? "0123456789OIZSGB" : "0123456789").split("");
    let seq = "";
    for (let k = 0; k < L.memoryLength; k++) seq += pool[Math.floor(rng() * pool.length)];

    /**
     * THE FOIL IS A CONFUSABLE. One character is swapped for one that LOOKS like it — 0/O,
     * 5/S, 8/B. A foil that differs obviously is a test of attention; a foil that differs
     * only in a character you can barely tell apart is a test of ENCODING, which is what we
     * actually want to measure. And the swap is internal, never the first or last character,
     * because the ends of a sequence are the easy parts.
     */
    const mi = 1 + Math.floor(rng() * Math.max(1, seq.length - 2));
    const orig = seq[mi];
    const conf = CONFUSABLES[orig] ?? [];
    let repl = orig;
    if (conf.length && rng() < 0.7) repl = conf[Math.floor(rng() * conf.length)];
    else {
      let guard = 0;
      do { repl = pool[Math.floor(rng() * pool.length)]; } while (repl === orig && guard++ < 12);
    }
    let foil = seq.slice(0, mi) + repl + seq.slice(mi + 1);
    if (foil === seq) foil = seq.slice(0, -1) + (seq.slice(-1) === "1" ? "2" : "1");

    const leftIsTrue = rng() < 0.5;
    out.push({
      id: `${gid}-s`, spawnAt: t, duration: L.memoryDisplayMs,
      kind: "distractor", decor: true, zone: "center",
      position: [0, 1.5, CENTRAL_Z],
      color: TEAL, emissive: TEAL, shape: "diamond", scale: 0.001,
      label: seq, meta: { labelInside: true, labelSize: 0.062, labelColor: TEAL },
    });
    out.push({
      id: `${gid}-d`, spawnAt: t + L.memoryDisplayMs, duration: 350,
      kind: "distractor", decor: true, zone: "center",
      position: [0, 1.5, CENTRAL_Z],
      color: GRAY, emissive: GRAY, shape: "diamond", scale: 0.001,
      label: "...", meta: { labelInside: true, labelSize: 0.06, labelColor: GRAY },
    });
    const probeAt = t + L.memoryDisplayMs + 350;
    for (const [side, val] of [[-1, leftIsTrue ? seq : foil], [1, leftIsTrue ? foil : seq]] as [number, string][]) {
      out.push({
        id: `${gid}-o${side < 0 ? "L" : "R"}`, spawnAt: probeAt, duration: 2000,
        kind: "distractor", decor: true, zone: "center",
        position: [side * 0.26, 1.5, CENTRAL_Z],
        color: WHITE, emissive: WHITE, shape: "diamond", scale: 0.001,
        label: val, meta: { labelInside: true, labelSize: 0.05, labelColor: WHITE },
      });
    }
    out.push({
      id: `${gid}-a`, spawnAt: probeAt, duration: 2000,
      kind: "go", zone: "center",
      position: [0, 1.5, CENTRAL_Z],
      requiredHand: leftIsTrue ? "left" : "right",
      color: WHITE, shape: "diamond", scale: 0.001,
      meta: { triggerTarget: true, central: true, ctask: "memory" },
    });
    t = probeAt + 2000 + L.minInt + rng() * (L.maxInt - L.minInt);
    n++;
  }

  return out.sort((a, b) => a.spawnAt - b.spawnAt);
}

const levels: ProgressionLevel[] = Array.from({ length: 315 }, (_, i) => {
  const L = ccLevel(i + 1);
  const task = L.centralMode === "goNoGo" ? "GO/NO-GO" : L.centralMode.toUpperCase();
  const per = L.peripheralMode === "purple" ? "P" : L.peripheralMode === "pt" ? "P+T" : "P+T+B";
  return {
    level: i + 1,
    label: `L${i + 1} · ${task} · ${per} · ${L.stimSize.toUpperCase()} · bias ${L.cpIndex}/7 · ${L.goWindow}ms`,
    parameters: { level: i + 1 } as Record<string, unknown>,
  };
});

export const CognitiveCrossfire: DrillDefinition = {
  id: "cognitive-crossfire",
  name: "Cognitive Crossfire",
  shortName: "Crossfire",
  phase: "Synchronize",
  interaction: "touch",
  responseMode: "strike",
  dualInput: true,
  authoredLadder: true,
  environment: "arena",
  mvp: true,
  hardStop: true,
  description: "60 seconds. TWO tasks at once. Solve the cognitive problem at the centre with your TRIGGERS while your HANDS strike the orbs appearing out in the field. 315 levels: the central task cycles Go/No-Go → math → memory, the orbs shrink and gain colours, and the spatial bias pushes them further and further out — until every orb costs you a saccade away from the problem.",
  purpose: "Divided attention — peripheral acquisition under a concurrent central cognitive load.",
  instructions: [
    "1. TWO TASKS AT ONCE. This is the whole drill. Do not do them one at a time.",
    "2. CENTRE (triggers): GREEN disc = pull the RIGHT trigger. RED disc = pull NOTHING.",
    "3. CENTRE (math/memory): two answers appear. LEFT trigger takes the left, RIGHT the right.",
    "4. PERIPHERY (hands): STRIKE the orbs as they appear. They do not expire - they just cost you time.",
    "5. 60 seconds. Both scores are reported. Collapsing on one to save the other is the failure this finds.",
  ],
  controlsHint: "HANDS = ORBS  ·  TRIGGERS = THE PROBLEM  ·  RED = WITHHOLD",
  levels,
  buildTrials: (params, rng) => buildCCTrials(ccLevel((params.level as number) ?? 1), rng),

  /**
   * THE DUAL-TASK COST is the number that matters, and neither task alone can show it. An
   * athlete who is excellent at both separately and falls apart when they run together has a
   * divided-attention ceiling — which is exactly what a crowded field punishes, and exactly
   * what a single-task drill cannot see.
   */
  analyze: (events) => {
    /**
     * A peripheral orb NEVER expires (duration > session), so the only way one can produce an
     * omission is the buzzer: when the 60s hard stop fires, the engine expires whatever is
     * still on the field. That is not a miss the athlete made — it is three orbs that were
     * alive when time ran out, and scoring them as misses would dock every athlete exactly
     * three errors for the crime of the clock stopping.
     */
    const per = events.filter((e) => e.trialId.startsWith("cc-p") && e.errorType !== "miss");
    const cen = events.filter((e) => e.trialId.startsWith("cc-c") && e.errorType !== "correctRejection");
    const cr = events.filter((e) => e.trialId.startsWith("cc-c") && e.errorType === "correctRejection");
    if (!per.length && !cen.length) return [];

    const m = (v: number[]) => (v.length ? Math.round(v.reduce((a, b) => a + b, 0) / v.length) : 0);
    const perRT = m(per.filter((e) => e.correct && e.reactionMs !== undefined).map((e) => e.reactionMs!));
    const cenAcc = cen.length
      ? Math.round(((cen.filter((e) => e.correct).length + cr.length) / (cen.length + cr.length)) * 100)
      : 0;
    const cenRT = m(cen.filter((e) => e.correct && e.reactionMs !== undefined).map((e) => e.reactionMs!));

    const notes = [
      `Peripheral: ${per.filter((e) => e.correct).length} orbs cleared, ${perRT}ms mean pickup.`,
      `Central: ${cenAcc}% correct, ${cenRT}ms mean decision.`,
    ];
    if (cenAcc >= 85 && per.filter((e) => e.correct).length < 12) {
      notes.push("The centre held and the periphery collapsed — the athlete is serialising: solving the problem, then looking up. That is the single-task strategy this drill exists to break.");
    } else if (cenAcc < 55 && per.filter((e) => e.correct).length > 25) {
      notes.push("The periphery held and the centre collapsed — the athlete is chasing orbs and abandoning the problem. The reaching hand is winning, and it should not be.");
    }
    return notes;
  },

  durationMs: () => SESSION_MS,
};
